In [1]:
### Libraries used: Tensorflow > 2.0 and keras

#!pip install tensorflow

  Created wheel for termcolor: filename=termcolor-1.1.0-py3-none-any.whl size=4829 sha256=135d28d88afd34b8c8c6e3e94e49465aebc88b1294b35eb54d272e8553b84beb
  Stored in directory: c:\users\kamil\appdata\local\pip\cache\wheels\a0\16\9c\5473df82468f958445479c59e784896fa24f4a5fc024b0f501
Successfully built termcolor


In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]
     

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
#Vocabulary size
voc_size = 10000

### One Hot Encoding    

In [7]:
onehot_repr=[one_hot(words,voc_size) for words in sent]
onehot_repr

[[9806, 3646, 3452, 8607],
 [9806, 3646, 3452, 6924],
 [9806, 3540, 3452, 9825],
 [470, 7269, 8113, 5713, 4470],
 [470, 7269, 8113, 5713, 2965],
 [3175, 9806, 7080, 3452, 9588],
 [8260, 3428, 9129, 5713]]

### Word Embedding Representation


In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

import numpy as np

In [9]:
#Fill in the space with zeros so that all sentences are of the same lengths
sent_length = 8
embedded_docs = pad_sequences(onehot_repr, padding = 'pre',maxlen=sent_length)
embedded_docs

array([[   0,    0,    0,    0, 9806, 3646, 3452, 8607],
       [   0,    0,    0,    0, 9806, 3646, 3452, 6924],
       [   0,    0,    0,    0, 9806, 3540, 3452, 9825],
       [   0,    0,    0,  470, 7269, 8113, 5713, 4470],
       [   0,    0,    0,  470, 7269, 8113, 5713, 2965],
       [   0,    0,    0, 3175, 9806, 7080, 3452, 9588],
       [   0,    0,    0,    0, 8260, 3428, 9129, 5713]])

In [11]:
dim = 10


In [12]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')


In [13]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [14]:
model.predict(embedded_docs)


array([[[-0.04612576, -0.02552131,  0.00759486,  0.00883349,
          0.03373304, -0.02752751,  0.03951133,  0.04935961,
          0.02494946, -0.04543444],
        [-0.04612576, -0.02552131,  0.00759486,  0.00883349,
          0.03373304, -0.02752751,  0.03951133,  0.04935961,
          0.02494946, -0.04543444],
        [-0.04612576, -0.02552131,  0.00759486,  0.00883349,
          0.03373304, -0.02752751,  0.03951133,  0.04935961,
          0.02494946, -0.04543444],
        [-0.04612576, -0.02552131,  0.00759486,  0.00883349,
          0.03373304, -0.02752751,  0.03951133,  0.04935961,
          0.02494946, -0.04543444],
        [-0.03827087,  0.03281777,  0.02688749, -0.0366254 ,
          0.04456732,  0.04709481,  0.04682083,  0.02740628,
         -0.01828287, -0.0290116 ],
        [ 0.040556  , -0.0450149 ,  0.03233821,  0.00443522,
         -0.03094921, -0.02836542,  0.02917799, -0.01165788,
         -0.00054879, -0.01562511],
        [-0.02369906, -0.00946314,  0.03088713,  0.0

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 9806, 3646, 3452, 8607])

In [17]:
model.predict(embedded_docs)[0]


array([[-0.04612576, -0.02552131,  0.00759486,  0.00883349,  0.03373304,
        -0.02752751,  0.03951133,  0.04935961,  0.02494946, -0.04543444],
       [-0.04612576, -0.02552131,  0.00759486,  0.00883349,  0.03373304,
        -0.02752751,  0.03951133,  0.04935961,  0.02494946, -0.04543444],
       [-0.04612576, -0.02552131,  0.00759486,  0.00883349,  0.03373304,
        -0.02752751,  0.03951133,  0.04935961,  0.02494946, -0.04543444],
       [-0.04612576, -0.02552131,  0.00759486,  0.00883349,  0.03373304,
        -0.02752751,  0.03951133,  0.04935961,  0.02494946, -0.04543444],
       [-0.03827087,  0.03281777,  0.02688749, -0.0366254 ,  0.04456732,
         0.04709481,  0.04682083,  0.02740628, -0.01828287, -0.0290116 ],
       [ 0.040556  , -0.0450149 ,  0.03233821,  0.00443522, -0.03094921,
        -0.02836542,  0.02917799, -0.01165788, -0.00054879, -0.01562511],
       [-0.02369906, -0.00946314,  0.03088713,  0.045936  ,  0.01819256,
        -0.03797735,  0.03256266,  0.01336498